### ISSUE TITLE
Use grunt processhtml, minify, uglify to combine CSS and JS scripts, and HTML

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#10]
- Gruntify the whole project! :smile:

**Comment by aniarya82** [comment]
how to gruntify it, at this point in the project????

**Comment by icyflame** [comment]
This is a very early stage, so, I would prefer to do it right now, and then build on it.

Use the project structure as in http://github.com/icyflame/hi

**Comment by icyflame** [comment]
Closed in favour of PHP. :smile:
