### ISSUE TITLE
Fix navbar rendering on small screens

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#15]
I don't understand why the navbar isn't collapsing :- 

![image](https://cloud.githubusercontent.com/assets/3668034/8888010/eafe8e7e-32b8-11e5-9d21-aa656d04a70a.png)

**Comment by aniarya82** [comment]
We gotta use bootstrap navbar for that

**Comment by icyflame** [comment]
Yes, if you plan to use a complete navbar, then you must use Bootstrap Navbar.

**Comment by icyflame** [comment]
Navbar button is not showing up on small screens.

![image](https://cloud.githubusercontent.com/assets/3668034/8889249/faab0794-32ef-11e5-83a5-fab7d7201360.png)

The solution is probably to make it's color `white`.
