### ISSUE TITLE
Remove the sponsors and gallery pages from navbar for now.

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#21]

**Comment by aniarya82** [comment]
Why??

**Comment by icyflame** [comment]
I just had a talk with Akash, and it seems that they want a simple gallery.

So, for nor, remove the navbar links, so that the page is deployable. After we are done with this, we will put it in.

We are going to design the gallery ourself, using the plugin: http://callmecavs.github.io/layzr.js/

It's really easy to use, and will give great results.

**Comment by icyflame** [comment]
As images for both these pages have been added on the server, and have not been checked into Git, these pages are functional.

Closing this now.
