### ISSUE TITLE
Put image in last meet inside a div.container-fluid element

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#39]
https://github.com/students-alumni-cell-iitkgp/aam-2016/pull/34#discussion_r36040525

**Comment by aniarya82** [comment]
It won't happen. I already tried it beforehand.

**Comment by icyflame** [comment]
@aniarya82 Solved in https://github.com/students-alumni-cell-iitkgp/aam-2016/commit/b0a97a72e615ce7585f7f51ee518ceb0d1fa9de2
