### ISSUE TITLE
Hide the red line, and center-align logo on smaller screens

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#5]
![image](https://cloud.githubusercontent.com/assets/3668034/8867229/b3403ea8-31e4-11e5-9d62-296a198f1245.png)
- Remove red line on smaller screens
- Center align logo
- Center align the register button

**Comment by aniarya82** [comment]
I previously removed the red line but Pranshu insisted to keep it.

For the time being i added a red margin to the image but that doesn't do the job for small screen devices.

You got any suggestion on how to keep the red line.

**Comment by icyflame** [comment]
I don't have a problem with the red line itself. It can stay, but what it should be hidden on smaller devices.

You can use `hidden-*` and `visible-*` classes, provided by Bootstrap, to get this functionality.
