### ISSUE TITLE
Move the alert code to a separate file `alert.php` and include it everywhere

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#57]

**Comment by aniarya82** [comment]
Yeah i was planning on doing it when the previous pr gets merged

**Comment by icyflame** [comment]
@aniarya82 

yeah, of course. Solve this once #50 get's merged.

**Comment by icyflame** [comment]
@aniarya82 You can solve and open a PR for this now.

**Comment by icyflame** [comment]
Stale.
