### ISSUE TITLE
Add sponsor links in the spons 2016 page

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#68]
@students-alumni-cell-iitkgp/web-team-members One of you needs to do this.

**Comment by uagarwal744** [comment]
@icyflame I can do this but how do I get the links

**Comment by icyflame** [comment]
@uagarwal744 You can google for most companies, and if you can't find then tell me.

**Comment by icyflame** [comment]
Fixed in #69
