### ISSUE TITLE
Add the site icon

### ISSUE THREAD

**Issue by icyflame** [students-alumni-cell-iitkgp/aam-2016#9]
- `rel="icon"`

**Comment by icyflame** [comment]
This doesn't really work on GItHub. 

Instead of using `/img/logo.png`, use `img/logo.png`.

Using the prefixed `/` will make it search for it at site root.

**Comment by icyflame** [comment]
You must use a square image as the site icon.

The image `img/logo.png` is a rectangular one. Crop the white space at the top and bottom, and then, use it as the site icon.

**Comment by icyflame** [comment]
Use a PNG transparent image as the site icon.

Please send the JPG to the design team and get a transparent one for the site icon.

The present one looks bad when we are on some other tab. (Due to the white background)

**Comment by aniarya82** [comment]
You need a Square and transparent Logo for both the site icon and image in the page right..

And delete all other previous logo

**Comment by icyflame** [comment]
I want four logos inside the img/ folder

`logo.jpg` (rectangle)
`logo.png` (transparent, rectangle)
`logo-square.jpg` (square)
`logo-square.png` (transparent, square)

**Comment by aniarya82** [comment]
okay i have mail ashay for transparency.

Will add as soon as i here from him.
